codecov:
  require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 75%
        threshold: 10% # Lower this when codecov becomes a mandatory pass
    patch: off
